services:
  - type: web
    name: sprintdesk
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist

    routes:
      - type: rewrite
        source: /*
        destination: /index.html